### PR TITLE
downgrade debase

### PR DESCRIPTION
**Pull request by ViugiNick**

### CODE REVIEW

**Comment by philipbjorge** [comment]
Why was this done?

**Comment by ViugiNick** [comment]
@philipbjorge We will release 0.2.5 in a few weeks

**Comment by wagenet** [comment]
@ViugiNick that still doesn't answer why. Was there a critical security vulnerability? If so, that should be disclosed. If not, yanking is pretty heavy handed.

**Comment by ViugiNick** [comment]
@wagenet @philipbjorge There was a problem with the integration of debase-0.2.5 with one of the IDE-s because of version advance, we will try to fix and release it ASAP. Apologize for any inconvenience caused

**Comment by wagenet** [comment]
@ViugiNick thanks for the update :)

**Pull request closed without merging**
